# Generated by Selenium IDE
from selenium import webdriver
from selenium.webdriver.common.by import By


class TestSelenium():
    def setup_method(self, method):
        self.driver = webdriver.Chrome()
        self.vars = {}

    def teardown_method(self, method):
        self.driver.quit()

    def test_selenium(self):
        self.driver.get("http://127.0.0.1:5000/")
        self.driver.set_window_size(1854, 1048)
        self.driver.find_element(By.LINK_TEXT, "Doe, Jane").click()
        self.driver.find_element(By.LINK_TEXT, "Home").click()
        self.driver.find_element(By.LINK_TEXT, "Doe, John").click()
        self.driver.find_element(By.LINK_TEXT, "Home").click()
        self.driver.find_element(By.CSS_SELECTOR, ".card:nth-child(1) .row > .text-secondary").click()
        self.driver.find_element(By.CSS_SELECTOR, ".card:nth-child(1) .row:nth-child(5)").click()
        self.driver.find_element(By.LINK_TEXT, "Home").click()
        self.driver.find_element(By.CSS_SELECTOR, ".card:nth-child(2) .row > .text-secondary").click()
        self.driver.find_element(By.LINK_TEXT, "Doe, John").click()
        self.driver.find_element(By.CSS_SELECTOR, ".sidebar-item:nth-child(2) .align-middle:nth-child(2)").click()
