"""empty message

Revision ID: 2173bfe555cb
Revises: 0c3d4c18067c
Create Date: 2024-12-14 00:27:20.934808

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2173bfe555cb'
down_revision = '0c3d4c18067c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('feature_model', schema=None) as batch_op:
        batch_op.add_column(sa.Column('features', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('constraints', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('feature_model', schema=None) as batch_op:
        batch_op.drop_column('constraints')
        batch_op.drop_column('features')

    # ### end Alembic commands ###
