"""Initial migration

Revision ID: 782b03ee7c07
Revises: ec145a599bfb
Create Date: 2024-11-11 11:20:35.123153

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '782b03ee7c07'
down_revision = 'ec145a599bfb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dataset_rating',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('value', sa.Integer(), nullable=False),
        sa.Column('comment', sa.Text(), nullable=True),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('dataset_id', sa.Integer(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['dataset_id'], ['data_set.id'], ),
        sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dataset_rating')
    # ### end Alembic commands ###
