"""Added: flags for anonymize authors

Revision ID: 85711493892f
Revises: cd6c22277144
Create Date: 2024-11-10 12:18:24.590458

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85711493892f'
down_revision = 'cd6c22277144'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ds_meta_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('anonymized', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ds_meta_data', schema=None) as batch_op:
        batch_op.drop_column('anonymized')

    # ### end Alembic commands ###
