"""Modify fields: is_developer and github_username

Revision ID: cd6c22277144
Revises: 0e16b897611a
Create Date: 2024-11-09 12:09:42.449904

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'cd6c22277144'
down_revision = '0e16b897611a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('github_username', sa.String(length=256), nullable=True))
        batch_op.drop_column('github_user')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('github_user', mysql.VARCHAR(length=256), nullable=True))
        batch_op.drop_column('github_username')

    # ### end Alembic commands ###
