"""Initial migration

Revision ID: fb7bff7660e4
Revises: 782b03ee7c07
Create Date: 2024-11-12 00:02:17.240387

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'fb7bff7660e4'
down_revision = '782b03ee7c07'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dataset_rating', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ds_meta_data_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint('dataset_rating_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'ds_meta_data', ['ds_meta_data_id'], ['id'])
        batch_op.drop_column('dataset_id')

    with op.batch_alter_table('ds_meta_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rating_avg', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ds_meta_data', schema=None) as batch_op:
        batch_op.drop_column('rating_avg')

    with op.batch_alter_table('dataset_rating', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dataset_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('dataset_rating_ibfk_1', 'data_set', ['dataset_id'], ['id'])
        batch_op.drop_column('ds_meta_data_id')

    # ### end Alembic commands ###
